### ISSUE TITLE
Internal Server Error while creating JIRA issues: Cannot invoke method replaceAll() on null object

### ISSUE THREAD

**Issue by argentra-kumar** [hclproducts/appscan-issue-gateway#10]
![image](https://user-images.githubusercontent.com/17444546/51506582-ecfbe600-1e27-11e9-8f6e-1c00925608c5.png)

Dear Team,

I am able to call "POST pushjobs" and status is as follows.
./pushjobs.sh data.json
{"id":"410204f8-a519-4d90-a160-aa2f27a0cfec","status":"Created"}

but When I call "GET pushjobs", I am getting following Error. Could you please advise on this error. 
./getjobs.sh 410204f8-a519-4d90-a160-aa2f27a0cfec
{"id":"410204f8-a519-4d90-a160-aa2f27a0cfec","status":"Completed","errors":["Internal Server Error while creating JIRA issues: Cannot invoke method replaceAll() on null object"],"results":{}}

I am looking forward your favorable reply. 

Thanks in advance

**Comment by jonathanjbutler** [comment]
I'm guessing that it's an issue with the severitymap.

Are you providing one in your data.json file with the POST pushjobs requests?

If the severity that you get from an ASoC issue doesn't match up with an entry in the severity map you'll see this issue.

If this isn't the case then any more information would be helpful.

**Comment by jonathanjbutler** [comment]
Hmm yep seems like theres nothing wrong with the severity map. Now thinking something is happening when parsing the ASoC issues. I added a null check when parsing the issues and put out another release (v0.0.11). 

Please try this and see if you still see the same issue when you get a chance.

**Comment by argentra-kumar** [comment]
Dear Jonathan,

Thanks for your reply. It now returns exact error , which is jira certificate issue. I am now able to create the jira ticket using Rest API.

Thanks a lot
Yours sincerely
S.Indirakumar

**Comment by vayalo** [comment]
When I am trying to create Azure DevOps bugs through issue gateway with ASE, I am getting following error. Any idea ?
{
  "id": "xxxxx",
  "status": "Complete - Failed with errors",
  "errors": [
    "Internal Server Error: null"
  ]
}

**Comment by vinitasanghi** [comment]
Could you confirm which operation throws this error? Also, hope you are able to access Azure DevOps server from ASE environment. There is video with ASoC integration: https://www.youtube.com/watch?v=y48wVBFZLoY&t=38s in case it helps.
