### ISSUE TITLE
AIG does not add comment in ASoC & attachment is not added in JIRA Defect

### ISSUE THREAD

**Issue by brwhyte** [hclproducts/appscan-issue-gateway#2]
Behavior is similar to Issue #1 - when pushing a defect the JIRA ticket is created however the details attachment is not present and the comment is not added to ASoC Portal Discussion section.

Issue Gateway being used:  **appscan-issue-gateway-0.0.6**

Error Msg in Console Window:
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.9.RELEASE)

REST ERROR: Connecting to: org.springframework.http.client.SimpleClientHttpRespo
nse@6dc0ee7e
REST ERROR: Status Text = Bad Request
REST ERROR: Status Code = 400
REST ERROR: Response Body = sun.net.www.protocol.http.HttpURLConnection$HttpInpu
tStream@7d5323b8

Errors in Log file:
2018-07-16 10:43:52,094 DEBUG [pool-1-thread-1] c.h.a.i.j.JobManager [JobManager.java:52] {
  "id" : "9695c848-0deb-4b8d-b40c-30ff8af7c418",
  "status" : "Running - Retrieving AppScan issue reports",
  "errors" : [ ],
  "results" : { }
}
2018-07-16 10:43:52,094 DEBUG [pool-1-thread-1] c.h.a.i.j.JobManager [JobManager.java:52] {
  "id" : "9695c848-0deb-4b8d-b40c-30ff8af7c418",
  "status" : "Running - Retrieving AppScan issue reports",
  "errors" : [ ],
  "results" : { }
}
2018-07-16 10:43:54,600 DEBUG [pool-1-thread-1] c.h.a.i.j.JobManager [JobManager.java:52] {
  "id" : "9695c848-0deb-4b8d-b40c-30ff8af7c418",
  "status" : "Running - Submitting issues",
  "errors" : [ "An error occurred generating a report.  Received 400 from https://appscan.ibmcloud.com/api/v2/Apps/fcef174b-2060-e811-9423-002590ac753d/Issues/CreateReport" ],
  "results" : { }
}
2018-07-16 10:43:54,600 DEBUG [pool-1-thread-1] c.h.a.i.j.JobManager [JobManager.java:52] {
  "id" : "9695c848-0deb-4b8d-b40c-30ff8af7c418",
  "status" : "Running - Submitting issues",
  "errors" : [ "An error occurred generating a report.  Received 400 from https://appscan.ibmcloud.com/api/v2/Apps/fcef174b-2060-e811-9423-002590ac753d/Issues/CreateReport" ],
  "results" : { }
}
2018-07-16 10:43:55,986 DEBUG [pool-1-thread-1] c.h.a.i.j.JobManager [JobManager.java:52] {
  "id" : "9695c848-0deb-4b8d-b40c-30ff8af7c418",
  "status" : "Running - Updating AppScan issues",
  "errors" : [ "An error occurred generating a report.  Received 400 from https://appscan.ibmcloud.com/api/v2/Apps/fcef174b-2060-e811-9423-002590ac753d/Issues/CreateReport", "Internal Server Error while creating JIRA issues: Ambiguous method overloading for method java.io.FileReader#<init>.\nCannot resolve which method to invoke for [null] due to overlapping prototypes between:\n\t[class java.lang.String]\n\t[class java.io.File]\n\t[class java.io.FileDescriptor]" ],
  "results" : { }
}
2018-07-16 10:43:55,986 DEBUG [pool-1-thread-1] c.h.a.i.j.JobManager [JobManager.java:52] {
  "id" : "9695c848-0deb-4b8d-b40c-30ff8af7c418",
  "status" : "Running - Updating AppScan issues",
  "errors" : [ "An error occurred generating a report.  Received 400 from https://appscan.ibmcloud.com/api/v2/Apps/fcef174b-2060-e811-9423-002590ac753d/Issues/CreateReport", "Internal Server Error while creating JIRA issues: Ambiguous method overloading for method java.io.FileReader#<init>.\nCannot resolve which method to invoke for [null] due to overlapping prototypes between:\n\t[class java.lang.String]\n\t[class java.io.File]\n\t[class java.io.FileDescriptor]" ],
  "results" : { }
}
2018-07-16 10:43:55,989 DEBUG [pool-1-thread-1] c.h.a.i.j.JobManager [JobManager.java:52] {
  "id" : "9695c848-0deb-4b8d-b40c-30ff8af7c418",
  "status" : "Completed",
  "errors" : [ "An error occurred generating a report.  Received 400 from https://appscan.ibmcloud.com/api/v2/Apps/fcef174b-2060-e811-9423-002590ac753d/Issues/CreateReport", "Internal Server Error while creating JIRA issues: Ambiguous method overloading for method java.io.FileReader#<init>.\nCannot resolve which method to invoke for [null] due to overlapping prototypes between:\n\t[class java.lang.String]\n\t[class java.io.File]\n\t[class java.io.FileDescriptor]" ],
  "results" : { }
}
2018-07-16 10:43:55,989 DEBUG [pool-1-thread-1] c.h.a.i.j.JobManager [JobManager.java:52] {
  "id" : "9695c848-0deb-4b8d-b40c-30ff8af7c418",
  "status" : "Completed",
  "errors" : [ "An error occurred generating a report.  Received 400 from https://appscan.ibmcloud.com/api/v2/Apps/fcef174b-2060-e811-9423-002590ac753d/Issues/CreateReport", "Internal Server Error while creating JIRA issues: Ambiguous method overloading for method java.io.FileReader#<init>.\nCannot resolve which method to invoke for [null] due to overlapping prototypes between:\n\t[class java.lang.String]\n\t[class java.io.File]\n\t[class java.io.FileDescriptor]" ],
  "results" : { }
}

**Comment by manoj-kum** [comment]
I had to modify the issue PolicyID to pass the value  ["00000000-0000-0000-0000-000000000000" ] as default, instead of an empty string. This fixed the issue.
