### ISSUE TITLE
The README.md under providers/vsts doesn't show the required "appscanProvider" option.

### ISSUE THREAD

**Issue by kjweinert** [hclproducts/appscan-issue-gateway#28]
**.../providers/vsts/README.md**
{
  "appscanData": {
    "url": "https://cloud.appscan.com",

Should be

"appscanData": {
    "appscanProvider": "ASOC",
    "url": "https://cloud.appscan.com"",

Or just dissapear the file since it is the only provider with a readme.

**Comment by knowds** [comment]
Readme for VSTS provider has been updated.
