### ISSUE TITLE
Cannot Deserialize AppScan Issue Object

### ISSUE THREAD

**Issue by cwtravis** [hclproducts/appscan-issue-gateway#3]
Getting the following error when using the AppScan Issue Gateway:

REST ERROR: Connecting to: org.springframework.http.client.SimpleClientHttpResponse@3dde06cd
REST ERROR: Status Text = Internal Server Error
REST ERROR: Status Code = 500
REST ERROR: Response Body = sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@711692bc

The call is failing and not returning a proper set of AppScan Issue objects, so the logs have a deserialization error.

2018-11-20 11:39:57,031 ERROR [pool-1-thread-1] c.h.a.i.i.h.IssueRetrievalHandler [IssueRetrievalHandler.java:61] Internal Server Error while retrieving AppScan Issues
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Can not deserialize instance of com.hcl.appscan.issuegateway.issues.AppScanIssue[] out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of com.hcl.appscan.issuegateway.issues.AppScanIssue[] out of START_OBJECT token
 at [Source: java.io.PushbackInputStream@1d5a76f9; line: 1, column: 1]

**Comment by sergio-ruivace** [comment]
I am getting the same error

**Comment by jonathanjbutler** [comment]
Looks like that 500 error is coming from the ASoC rest api when trying to get the issues.  Will continue to investigate.

**Comment by sergioruivace** [comment]
Yes, but the API is working properly on Swagger page (https://appscan.ibmcloud.com/swagger/ui/index). Maybe they have changed some details on API.

**Comment by jonathanjbutler** [comment]
There is an issue with the ASoC rest api now requiring the Accept-Language header. The swagger page included this header, but the suggested curl command does not. The issue gateway is now updated to include the header in release 0.0.8
